### ISSUE TITLE
Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'device_id' in 'field list' in /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php:561 Stack trace: 

### ISSUE THREAD

**Issue by diloabininyeri** [PHPAuth/PHPAuth#514]
my Auth class 

```
<?php

namespace Acl;

use Closure;
use Illuminate\Database\Capsule\Manager;
use PDO;
use PHPAuth\Auth as PHPAuth;
use PHPAuth\Config as PHPAuthConfig;

/**
 *
 */
class Auth
{
    /**
     * @var array|null
     */
    private ?array $user;

    /**
     *
     */
    public function __construct()
    {
        $this->user = $this->getCurrentUser();
    }

    /**
     * @return array
     */
    public function user(): array
    {
        return $this->user ?: [];
    }

    /**
     * @return bool
     */
    public function isLogin(): bool
    {
        return $this->getComponent()->isLogged();
    }

    /**
     * @return array|null
     */
    private function getCurrentUser(): ?array
    {
        return $this->getComponent()->getCurrentUser();
    }

    /**
     * @return PHPAuth
     */
    public function getComponent(): PHPAuth
    {
        $pdo = $this->getPdoInstance();
        $config = new PHPAuthConfig($pdo, '', '', 'tr_TR');
        return new PHPAuth(
            $pdo,
            $config
        );
    }

    /**
     * @return PDO
     */
    public function getPdoInstance(): PDO
    {
        $config = $this->getConfig();
        $dsn = sprintf(
            '%s:host=%s;dbname=%s',
            $config['driver'],
            $config['host'],
            $config['database']
        );
        return new PDO($dsn, $config['username'], $config['password']);
    }

    /**
     * @return array{driver:string,host:string,database:string,username:string,password:string}
     */
    private function getConfig(): array
    {
        return Manager::connection()->getConfig();
    }

    /**
     * @param Closure|null $closure
     * @return bool
     */
    public function logout(Closure $closure = null): bool
    {
        $hash = $_COOKIE['phpauth_session_cookie'] ?? '';
        $isLogout = $this->getComponent()->logout($hash);
        if ($isLogout) {
            $closure();
        }

        return $isLogout;
    }
}

```

and usage 
```

$auth=new Auth();

```
but given error as such 

```
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'device_id' in 'field list' in /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php:561 Stack trace: #0 /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php(561): PDOStatement->execute() #1 /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php(1651): PHPAuth\Auth->checkSession() #2 /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php(79): PHPAuth\Auth->isLogged() #3 /home/dppop/Desktop/acl/src/Auth.php(63): PHPAuth\Auth->__construct() #4 /home/dppop/Desktop/acl/src/Auth.php(26): Acl\Auth->getComponent() #5 /home/dppop/Desktop/acl/index.php(39): Acl\Auth->__construct() #6 {main} thrown in /home/dppop/Desktop/acl/vendor/phpauth/phpauth/Auth.php on line 561

```

**Comment by louis123562** [comment]
Hey, sorry for answering that late. The error message means, that in your database-table 'phpauth_sessions', the column "device_id" is missing. 

Maybe you can compare your current database-structure with the one here (https://github.com/PHPAuth/PHPAuth/blob/master/database_defs/database_mysql.sql) and add the missing columns? It should work then :)

**Comment by diloabininyeri** [comment]
I took over the project from another developer, thanks it worked for now :smile:
